all:
  amazon_sqs_test_queue: '' #optional. It is required for tests
  test:
    test: 'test' # don't chage!!!
  driver:
    class: 'fpMqAmazonQueue' #TODO implement. It doesn't work now
    prefix: ''
    sender: ''
    options:
      name: '' #Required
      driverOptions:
        id: '' #Required
        key: '' #Required
test:
  test:
    test: 'test2' # don't chage!!!
