all:
  amazon_sqs_test_queue: '' #optional. It is required for tests
  test:
    test: 'test' # don't chage!!!
  driver:
    class: 'Zend_Queue_Adapter_Rabbitmq'
    prefix: '' #optional
    sender: '' #optional if it sets own message will be ignored
    options:
      name: '' #Default queue name. Required for Amazone SQS
      exchange: #RabbitMQ Required
        name: topic
#      driverOptions: #Amazone SQS
#        id: '' #Required
#        key: '' #Required
#      driverOptions: #Memcacheq optional
#        port: 22201
#        host: 127.0.0.1
#      driverOptions: #RabbitMQ optional. It can be set in php.ini
#        host: /
#        port: 5672
#        login: guest
#        password: guest
test:
  test:
    test: 'test2' # don't chage!!!
