all:
  amazon_sqs_test_queue: '' #optional. It is required for tests
  test:
    test: 'test' # don't chage!!!
  driver:
    class: 'fpMqAmazonQueue' #TODO implement. It doesn't work now
    prefix: ''
    sender: ''
    options:
      name: '' #Required for Amazone SQS
      exchange:
        name: topic
      driverOptions:
        id: '' #Required for Amazone SQS
        key: '' #Required for Amazone SQS
        port: 22201 #Optional for Memcacheq
        host: 127.0.0.1 #Optional for Memcacheq

test:
  test:
    test: 'test2' # don't chage!!!
